# Site settings
name: Vaishnav Potlapalli
title: Vaishnav Potlapalli | ML Engineer
description: A ML and Computer Vision enthusiast
url: https://bchiang7.github.io/
baseurl: ''
email: pvaishnav2718@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:pvaishnav2718@gmail.com

  # - title: instagram
  #   url: https://instagram.com/bchiang7
  # - title: codepen
  #   url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/va1shn9v
  - title: linkedin
    url: https://www.linkedin.com/in/vaishnav-potlapalli/
  - title: twitter
    url: https://twitter.com/__vaishnav

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
